//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.DATACLIENT = new HashSet<DATACLIENT>();
            this.EXERCISESFORCLIENT = new HashSet<EXERCISESFORCLIENT>();
        }
    
        public string FIRSTNAME { get; set; }
        public string SECONDNAME { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public decimal ID_CLIENT { get; set; }
        public Nullable<decimal> NUMBER_GROUP { get; set; }
    
        public virtual GROUPFORCLIENT GROUPFORCLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATACLIENT> DATACLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXERCISESFORCLIENT> EXERCISESFORCLIENT { get; set; }
    }
}
