//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATACLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATACLIENT()
        {
            this.WORKOUT = new HashSet<WORKOUT>();
        }
    
        public decimal ID_DATACLIENT { get; set; }
        public decimal ID_CLIENT { get; set; }
        public decimal WEIGHT { get; set; }
        public decimal HEIGHT { get; set; }
        public string BODYTYPE { get; set; }
        public Nullable<decimal> PROGRESS_WEIGHT { get; set; }
        public Nullable<decimal> PROGRESS_POWER { get; set; }
        public Nullable<System.DateTime> DATETIME { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKOUT> WORKOUT { get; set; }
    }
}
