//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATATRAINER
    {
        public decimal ID_TRAINER { get; set; }
        public decimal WEIGHT { get; set; }
        public decimal HEIGHT { get; set; }
        public decimal BARBELLSQUAT { get; set; }
        public decimal DEADLIFT { get; set; }
        public decimal BENCHPRESS { get; set; }
        public decimal PULLUPS { get; set; }
        public string BODYTYPE { get; set; }
    
        public virtual TRAINER TRAINER { get; set; }
    }
}
