//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXERCISES
    {
        public string EXERCISES1 { get; set; }
        public string MUSCLEGROUPS { get; set; }
        public Nullable<decimal> PRIORETY { get; set; }
    }
}
