//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGES
    {
        public string MESSAGES1 { get; set; }
        public decimal ID_MESSAGE { get; set; }
        public decimal WHO_SENDER { get; set; }
        public decimal WHO_RECIPIENT { get; set; }
        public Nullable<decimal> GROUPMESSAGE { get; set; }
        public System.DateTime DATETIME { get; set; }
    }
}
