//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_KURSACH_Entities : DbContext
    {
        public BD_KURSACH_Entities()
            : base("name=BD_KURSACH_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENT> CLIENT { get; set; }
        public virtual DbSet<DATACLIENT> DATACLIENT { get; set; }
        public virtual DbSet<DATATRAINER> DATATRAINER { get; set; }
        public virtual DbSet<EXERCISES> EXERCISES { get; set; }
        public virtual DbSet<EXERCISESFORCLIENT> EXERCISESFORCLIENT { get; set; }
        public virtual DbSet<GROUPFORCLIENT> GROUPFORCLIENT { get; set; }
        public virtual DbSet<MESSAGES> MESSAGES { get; set; }
        public virtual DbSet<RESULTEXERCISES> RESULTEXERCISES { get; set; }
        public virtual DbSet<TRAINER> TRAINER { get; set; }
        public virtual DbSet<WORKOUT> WORKOUT { get; set; }
    }
}
