//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESULTEXERCISES
    {
        public decimal NUMBERWORKOUT { get; set; }
        public decimal ID_EXERCISES { get; set; }
        public string EXERCISES { get; set; }
        public Nullable<decimal> WEIGHT_FOR_EXERCISES { get; set; }
        public Nullable<decimal> QQUANTITY { get; set; }
        public string DAYFOREXERCISE { get; set; }
        public string MUSCLEGROUPS { get; set; }
        public Nullable<decimal> PRIORETY { get; set; }
    
        public virtual WORKOUT WORKOUT { get; set; }
    }
}
