//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINER
    {
        public string FIRSTNAME { get; set; }
        public string SECONDNAME { get; set; }
        public decimal ID_TRAINER { get; set; }
        public string PASSWORD { get; set; }
        public string LOGIN { get; set; }
        public Nullable<decimal> NUMBER_GROUP { get; set; }
    
        public virtual DATATRAINER DATATRAINER { get; set; }
        public virtual GROUPFORCLIENT GROUPFORCLIENT { get; set; }
    }
}
