//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKOUT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WORKOUT()
        {
            this.RESULTEXERCISES = new HashSet<RESULTEXERCISES>();
        }
    
        public decimal NUMBERWORKOUT { get; set; }
        public Nullable<decimal> ID_DATACLIENT { get; set; }
        public Nullable<decimal> PULSE { get; set; }
        public string DIFFICULTY_WORKOUT { get; set; }
        public string INTENSITY { get; set; }
        public Nullable<decimal> COUNTEXERCISES { get; set; }
        public Nullable<System.DateTime> DATETIME { get; set; }
    
        public virtual DATACLIENT DATACLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULTEXERCISES> RESULTEXERCISES { get; set; }
    }
}
